---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - var-repo.txt
 
  tasks:
  - name: Launch load balancing instance
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'ansible_group':'{{ ec2_tag_webservers }}', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ ec2_tag }}'}"
     count="{{ ec2_instance_count }}"
     count="1"
     wait=true
    register: ec2

  - name: Wait for SSH to come up
    local_action: wait_for host="{{ item.public_dns_name }}"
      port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"

  roles:
    - { role: nickjj.docker, tags: docker }
