---
- name: Create a Docker Compose Host for testing
  hosts: localhost
  gather_facts: False
  vars:
    key_name: generic-cloud-wk
    instance_type: m4.large
    security_group: cvaas
    image: ami-1d4e7a66
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
#         vpc_subnet_id: subnet-29e63245
#         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: launched
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Install Python
      raw: sudo apt install -y python-minimal

- hosts: launched
  sudo: yes
  roles:
    - ADC
  vars:
    docker_compose_version: 1.16.1

- hosts: launched
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    dev_version: "dev142"
  tasks:
    - name: Add Ubuntu user to Docker group
      user: name=ubuntu groups=docker append=yes

#    - name: Transfer CVaaS Testing Scripts  
#      copy:
#        src: /root/Moff/Projects/ATT/CVaaS/git-repo/stage-area/cicd/cvaas-test-script.sh
#        dest: /home/ubuntu/cvaas-test-script.sh
#        owner: ubuntu
#        group: ubuntu
#        mode: 0777

    - name: Stage CVaaS Load    
      unarchive: 
        src: /root/Moff/Projects/ATT/CVaaS/git-repo/stage-area/cvaas-staging/dist/cvaas-0.0.1.{{dev_version}}.tar.gz
        dest: /home/ubuntu/
        remote_src: yes

    - name: Build CVaaS image
      command: docker build -t cvaas /home/ubuntu/cvaas-0.0.1.{{dev_version}}/

    - name: Build and run CVaaS Ms
      command: docker-compose -f /home/ubuntu/cvaas-0.0.1.{{dev_version}}/docker-compose.yaml up -d --build --scale cvaas-worker=2

#    - name: Execute CVaaS Sanity test
#      shell: cvaas-test-script.sh >> cvaas-0.0.1.{{dev_version}}.log
#      args:
#        chdir: /home/ubuntu
#        creates: cvaas-0.0.1.{{dev_version}}.log  
            

