---
- name: Create a Docker Compose Host for testing
  hosts: localhost
  gather_facts: False
  vars:
    key_name: generic-cloud-wk
#    instance_type: m4.16xlarge
#    instance_type: m3.2xlarge
    instance_type: r4.2xlarge
    security_group: onap
    image: ami-1d4e7a66
    region: us-east-1
    count: 1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: "{{ count }}"
#         vpc_subnet_id: subnet-29e63245
#         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: launched
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt install -y python-minimal

- hosts: launched
  sudo: yes
  roles:
    - ADC
  vars:
    docker_compose_version: 1.16.1

- hosts: launched
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - user: name=ubuntu groups=docker append=yes

# README
# Resize the volume 60Gb then:
#https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html
# sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable
# http://rancher.com/docs/rancher/v1.6/en/quick-start-guide/
#https://wiki.onap.org/display/DW/ONAP+on+Kubernetes#ONAPonKubernetes-UndercloudInstallation
#
#https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169
#sudo mkdir /mnt/onap
#sudo chmod 777 /mnt/onap
#sudo service docker stop
#sudo mv /var/lib/docker /mnt/docker
#sudo ln -s /mnt/docker /var/lib/docker
#sudo service docker start